# TASK: 1 (Part 2)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv("House_Selling.csv")

In [3]:
df.head(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,Size of house (sqft)
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,7503

In [4]:
df.tail(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,Size of house (sqft)
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1357

In [5]:
df["price"]

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [6]:
df["price"][0]

221900.0

In [7]:
#load the data set
data = pd.read_csv('House_Selling.csv')
print(data.head()) #display first few rows
print(data.info())

           id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180
1  6414100192  20141209T000000  538000.0         3       2.25         2570
2  5631500400  20150225T000000  180000.0         2       1.00          770
3  2487200875  20141209T000000  604000.0         4       3.00         1960
4  1954400510  20150218T000000  510000.0         3       2.00         1680

   sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0      5650     1.0           0     0          3      7        1180
1      7242     2.0           0     0          3      7        2170
2     10000     1.0           0     0          3      6         770
3      5000     1.0           0     0          5      7        1050
4      8080     1.0           0     0          3      8        1680

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257
1            400      1951          1991    98125  47.7210 -122.319
2              0      1933             0    98028  47.7379 -122.233
3            910      1965             0    98136  47.5208 -122.393
4              0      1987             0    98074  47.6168 -122.045

   Size of house (sqft)
0                  5650
1                  7639
2                  8062
3                  5000
4                  7503
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  int64
 4   bathrooms             21613 non-null  float64
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  float64
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  Size of house (sqft)  21613 non-null  int64
dtypes: float64(5), int64(14), object(1)
memory usage: 3.3+ MB
None

In [13]:
X= data[['price', 'Size of house (sqft)']]
print(type(X))
print(X.shape)
print(X.head())

<class 'pandas.core.frame.DataFrame'>
(21613, 2)
      price  Size of house (sqft)
0  221900.0                  5650
1  538000.0                  7639
2  180000.0                  8062
3  604000.0                  5000
4  510000.0                  7503

In [11]:
#using elbow method
wcss = []
for i in range(1, 11):
    k_means = KMeans(n_clusters=i, n_init=10)
    k_means.fit(X)
    wcss.append(k_means.inertia_)

# the elbow curve
plt.plot(range(1, 11), wcss, linewidth=2.5, color="red", marker="8")
plt.title("Elbow Curve")
plt.xlabel("Number of clusters (values of k)")
plt.ylabel("WCSS values")
plt.xticks(np.arange(1, 11, 1))
plt.show()

C:\Users\waghi\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():

AttributeError: 'NoneType' object has no attribute 'split'

In [14]:
import sklearn
print(sklearn.__version__)

1.0.2